// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvmWuaP61WhIyyRTnB685PvlDVplhNBI',
    appId: '1:126805740008:web:1f80d67b4cc738982cbc5d',
    messagingSenderId: '126805740008',
    projectId: 'vocab-quiz-71c06',
    authDomain: 'vocab-quiz-71c06.firebaseapp.com',
    storageBucket: 'vocab-quiz-71c06.firebasestorage.app',
    measurementId: 'G-0SYF1LB8KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxGrNb2ZPOIMrcD4BX_lGSuaUJ3wd9LYA',
    appId: '1:126805740008:android:49923d723cd93d8a2cbc5d',
    messagingSenderId: '126805740008',
    projectId: 'vocab-quiz-71c06',
    storageBucket: 'vocab-quiz-71c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd6akoB1VM3SbqTh-2RYtmSqk5YZgL8Mo',
    appId: '1:126805740008:ios:08c9da555a20aa5f2cbc5d',
    messagingSenderId: '126805740008',
    projectId: 'vocab-quiz-71c06',
    storageBucket: 'vocab-quiz-71c06.firebasestorage.app',
    iosBundleId: 'com.vocabquiz.vocabQuiz',
  );

}